[package]
name = "laufen"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0"
winit = "0.30"
env_logger = "0.11"
log = "0.4"
wgpu = "28.0"
pollster = "0.4"
bytemuck = { version = "1.25", features = [ "derive" ] }
repr-trait = "1.0.0"
partially = { version = "0.2", features = [ "derive" ] }
renet = "2.0.0"
renet_netcode = "2.0.0"
rhai = "1.24.0"
glam = { version = "0.32" , features = [ "bytemuck" ] }
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
shipyard = "0.11.0"
getset = "0.1.6"
winit_input_helper = "0.17.0"
num-traits = "0.2.19"
stringid = "0.1.1"
cityhasher = "0.1.0"
itertools = "0.14.0"

